<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Angene.Common\Angene.Common.csproj" />
    <ProjectReference Include="..\Angene.Windows\Angene.Windows.csproj" />
    <ProjectReference Include="..\Angene.Vulkan\Angene.Vulkan.csproj" />
  </ItemGroup>

  <ItemGroup>
    	<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DX11\" />
  </ItemGroup>

</Project>
