<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup Condition="'$(AngenePlatform)' == 'Linux'">
      <EmbeddedResource Include="Native/linux-x64/libxdg-shell-client.so">
          <LogicalName>Angene.Linux.Native.linux-x64.libxdg-shell-client.so</LogicalName>
      </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Angene.Common\Angene.Common.csproj" />
  </ItemGroup>
</Project>
