namespace Angene.Windows.Dxgi
{
    public class DxgiEnums
    {
        public enum DXGI_FRAME_PRESENTATION_MODE : int
        {
            DXGI_FRAME_PRESENTATION_MODE_COMPOSED = 0,
            DXGI_FRAME_PRESENTATION_MODE_OVERLAY = 1,
            DXGI_FRAME_PRESENTATION_MODE_NONE = 2,
            DXGI_FRAME_PRESENTATION_MODE_COMPOSITION_FAILURE = 3
        }

        public enum DXGI_GRAPHICS_PREEMPTION_GRANULARITY : int
        {
            DXGI_GRAPHICS_PREEMPTION_DMA_BUFFER_BOUNDARY = 0,
            DXGI_GRAPHICS_PREEMPTION_PRIMITIVE_BOUNDARY = 1,
            DXGI_GRAPHICS_PREEMPTION_TRIANGLE_BOUNDARY = 2,
            DXGI_GRAPHICS_PREEMPTION_PIXEL_BOUNDARY = 3,
            DXGI_GRAPHICS_PREEMPTION_INSTRUCTION_BOUNDARY = 4
        }

        public enum DXGI_COMPUTE_PREEMPTION_GRANULARITY : int
        {
            DXGI_COMPUTE_PREEMPTION_DMA_BUFFER_BOUNDARY = 0,
            DXGI_COMPUTE_PREEMPTION_DISPATCH_BOUNDARY = 1,
            DXGI_COMPUTE_PREEMPTION_THREAD_GROUP_BOUNDARY = 2,
            DXGI_COMPUTE_PREEMPTION_THREAD_BOUNDARY = 3,
            DXGI_COMPUTE_PREEMPTION_INSTRUCTION_BOUNDARY = 4
        }

        public enum DXGI_INFO_QUEUE_MESSAGE_CATEGORY
        {
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_UNKNOWN = 0,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_MISCELLANEOUS,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_INITIALIZATION,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_CLEANUP,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_COMPILATION,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_CREATION,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_SETTING,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_GETTING,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_RESOURCE_MANIPULATION,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_EXECUTION,
            DXGI_INFO_QUEUE_MESSAGE_CATEGORY_SHADER
        }

        public enum DXGI_INFO_QUEUE_MESSAGE_SEVERITY
        {
            DXGI_INFO_QUEUE_MESSAGE_SEVERITY_CORRUPTION = 0,
            DXGI_INFO_QUEUE_MESSAGE_SEVERITY_ERROR,
            DXGI_INFO_QUEUE_MESSAGE_SEVERITY_WARNING,
            DXGI_INFO_QUEUE_MESSAGE_SEVERITY_INFO,
            DXGI_INFO_QUEUE_MESSAGE_SEVERITY_MESSAGE
        }

        public enum DXGI_FORMAT : uint
        {
            DXGI_FORMAT_UNKNOWN = 0,
            DXGI_FORMAT_R32G32B32A32_TYPELESS = 1,
            DXGI_FORMAT_R32G32B32A32_FLOAT = 2,
            DXGI_FORMAT_R32G32B32A32_UINT = 3,
            DXGI_FORMAT_R32G32B32A32_SINT = 4,
            DXGI_FORMAT_R32G32B32_TYPELESS = 5,
            DXGI_FORMAT_R32G32B32_FLOAT = 6,
            DXGI_FORMAT_R32G32B32_UINT = 7,
            DXGI_FORMAT_R32G32B32_SINT = 8,
            DXGI_FORMAT_R16G16B16A16_TYPELESS = 9,
            DXGI_FORMAT_R16G16B16A16_FLOAT = 10,
            DXGI_FORMAT_R16G16B16A16_UNORM = 11,
            DXGI_FORMAT_R16G16B16A16_UINT = 12,
            DXGI_FORMAT_R16G16B16A16_SNORM = 13,
            DXGI_FORMAT_R16G16B16A16_SINT = 14,
            DXGI_FORMAT_R32G32_TYPELESS = 15,
            DXGI_FORMAT_R32G32_FLOAT = 16,
            DXGI_FORMAT_R32G32_UINT = 17,
            DXGI_FORMAT_R32G32_SINT = 18,
            DXGI_FORMAT_R32G8X24_TYPELESS = 19,
            DXGI_FORMAT_D32_FLOAT_S8X24_UINT = 20,
            DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
            DXGI_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
            DXGI_FORMAT_R10G10B10A2_TYPELESS = 23,
            DXGI_FORMAT_R10G10B10A2_UNORM = 24,
            DXGI_FORMAT_R10G10B10A2_UINT = 25,
            DXGI_FORMAT_R11G11B10_FLOAT = 26,
            DXGI_FORMAT_R8G8B8A8_TYPELESS = 27,
            DXGI_FORMAT_R8G8B8A8_UNORM = 28,
            DXGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
            DXGI_FORMAT_R8G8B8A8_UINT = 30,
            DXGI_FORMAT_R8G8B8A8_SNORM = 31,
            DXGI_FORMAT_R8G8B8A8_SINT = 32,
            DXGI_FORMAT_R16G16_TYPELESS = 33,
            DXGI_FORMAT_R16G16_FLOAT = 34,
            DXGI_FORMAT_R16G16_UNORM = 35,
            DXGI_FORMAT_R16G16_UINT = 36,
            DXGI_FORMAT_R16G16_SNORM = 37,
            DXGI_FORMAT_R16G16_SINT = 38,
            DXGI_FORMAT_R32_TYPELESS = 39,
            DXGI_FORMAT_D32_FLOAT = 40,
            DXGI_FORMAT_R32_FLOAT = 41,
            DXGI_FORMAT_R32_UINT = 42,
            DXGI_FORMAT_R32_SINT = 43,
            DXGI_FORMAT_R24G8_TYPELESS = 44,
            DXGI_FORMAT_D24_UNORM_S8_UINT = 45,
            DXGI_FORMAT_R24_UNORM_X8_TYPELESS = 46,
            DXGI_FORMAT_X24_TYPELESS_G8_UINT = 47,
            DXGI_FORMAT_R8G8_TYPELESS = 48,
            DXGI_FORMAT_R8G8_UNORM = 49,
            DXGI_FORMAT_R8G8_UINT = 50,
            DXGI_FORMAT_R8G8_SNORM = 51,
            DXGI_FORMAT_R8G8_SINT = 52,
            DXGI_FORMAT_R16_TYPELESS = 53,
            DXGI_FORMAT_R16_FLOAT = 54,
            DXGI_FORMAT_D16_UNORM = 55,
            DXGI_FORMAT_R16_UNORM = 56,
            DXGI_FORMAT_R16_UINT = 57,
            DXGI_FORMAT_R16_SNORM = 58,
            DXGI_FORMAT_R16_SINT = 59,
            DXGI_FORMAT_R8_TYPELESS = 60,
            DXGI_FORMAT_R8_UNORM = 61,
            DXGI_FORMAT_R8_UINT = 62,
            DXGI_FORMAT_R8_SNORM = 63,
            DXGI_FORMAT_R8_SINT = 64,
            DXGI_FORMAT_A8_UNORM = 65,
            DXGI_FORMAT_R1_UNORM = 66,
            DXGI_FORMAT_R9G9B9E5_SHAREDEXP = 67,
            DXGI_FORMAT_R8G8_B8G8_UNORM = 68,
            DXGI_FORMAT_G8R8_G8B8_UNORM = 69,
            DXGI_FORMAT_BC1_TYPELESS = 70,
            DXGI_FORMAT_BC1_UNORM = 71,
            DXGI_FORMAT_BC1_UNORM_SRGB = 72,
            DXGI_FORMAT_BC2_TYPELESS = 73,
            DXGI_FORMAT_BC2_UNORM = 74,
            DXGI_FORMAT_BC2_UNORM_SRGB = 75,
            DXGI_FORMAT_BC3_TYPELESS = 76,
            DXGI_FORMAT_BC3_UNORM = 77,
            DXGI_FORMAT_BC3_UNORM_SRGB = 78,
            DXGI_FORMAT_BC4_TYPELESS = 79,
            DXGI_FORMAT_BC4_UNORM = 80,
            DXGI_FORMAT_BC4_SNORM = 81,
            DXGI_FORMAT_BC5_TYPELESS = 82,
            DXGI_FORMAT_BC5_UNORM = 83,
            DXGI_FORMAT_BC5_SNORM = 84,
            DXGI_FORMAT_B5G6R5_UNORM = 85,
            DXGI_FORMAT_B5G5R5A1_UNORM = 86,
            DXGI_FORMAT_B8G8R8A8_UNORM = 87,
            DXGI_FORMAT_B8G8R8X8_UNORM = 88,
            DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
            DXGI_FORMAT_B8G8R8A8_TYPELESS = 90,
            DXGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
            DXGI_FORMAT_B8G8R8X8_TYPELESS = 92,
            DXGI_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
            DXGI_FORMAT_BC6H_TYPELESS = 94,
            DXGI_FORMAT_BC6H_UF16 = 95,
            DXGI_FORMAT_BC6H_SF16 = 96,
            DXGI_FORMAT_BC7_TYPELESS = 97,
            DXGI_FORMAT_BC7_UNORM = 98,
            DXGI_FORMAT_BC7_UNORM_SRGB = 99,
            DXGI_FORMAT_AYUV = 100,
            DXGI_FORMAT_Y410 = 101,
            DXGI_FORMAT_Y416 = 102,
            DXGI_FORMAT_NV12 = 103,
            DXGI_FORMAT_P010 = 104,
            DXGI_FORMAT_P016 = 105,
            DXGI_FORMAT_420_OPAQUE = 106,
            DXGI_FORMAT_YUY2 = 107,
            DXGI_FORMAT_Y210 = 108,
            DXGI_FORMAT_Y216 = 109,
            DXGI_FORMAT_NV11 = 110,
            DXGI_FORMAT_AI44 = 111,
            DXGI_FORMAT_IA44 = 112,
            DXGI_FORMAT_P8 = 113,
            DXGI_FORMAT_A8P8 = 114,
            DXGI_FORMAT_B4G4R4A4_UNORM = 115,
            DXGI_FORMAT_P208 = 130,
            DXGI_FORMAT_V208 = 131,
            DXGI_FORMAT_V408 = 132,
            DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE = 189,
            DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE = 190,
            DXGI_FORMAT_A4B4G4R4_UNORM = 191,
            DXGI_FORMAT_FORCE_UINT = 0xffffffff
        }

        public enum DXGI_MODE_SCANLINE_ORDER
        {
            DXGI_MODE_SCANLINE_ORDER_UNSPECIFIED = 0,
            DXGI_MODE_SCANLINE_ORDER_PROGRESSIVE = 1,
            DXGI_MODE_SCANLINE_ORDER_UPPER_FIELD_FIRST = 2,
            DXGI_MODE_SCANLINE_ORDER_LOWER_FIELD_FIRST = 3
        }

        public enum DXGI_MODE_SCALING
        {
            DXGI_MODE_SCALING_UNSPECIFIED = 0,
            DXGI_MODE_SCALING_CENTERED = 1,
            DXGI_MODE_SCALING_STRETCHED = 2
        }

        public enum DXGI_MODE_ROTATION
        {
            DXGI_MODE_ROTATION_UNSPECIFIED = 0,
            DXGI_MODE_ROTATION_IDENTITY = 1,
            DXGI_MODE_ROTATION_ROTATE90 = 2,
            DXGI_MODE_ROTATION_ROTATE180 = 3,
            DXGI_MODE_ROTATION_ROTATE270 = 4
        }

        public enum DXGI_COLOR_SPACE_TYPE : uint
        {
            DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709 = 0,
            DXGI_COLOR_SPACE_RGB_FULL_G10_NONE_P709 = 1,
            DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P709 = 2,
            DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P2020 = 3,
            DXGI_COLOR_SPACE_RESERVED = 4,
            DXGI_COLOR_SPACE_YCBCR_FULL_G22_NONE_P709_X601 = 5,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P601 = 6,
            DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P601 = 7,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P709 = 8,
            DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P709 = 9,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P2020 = 10,
            DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P2020 = 11,
            DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020 = 12,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020 = 13,
            DXGI_COLOR_SPACE_RGB_STUDIO_G2084_NONE_P2020 = 14,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_TOPLEFT_P2020 = 15,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020 = 16,
            DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P2020 = 17,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_GHLG_TOPLEFT_P2020 = 18,
            DXGI_COLOR_SPACE_YCBCR_FULL_GHLG_TOPLEFT_P2020 = 19,
            DXGI_COLOR_SPACE_RGB_STUDIO_G24_NONE_P709 = 20,
            DXGI_COLOR_SPACE_RGB_STUDIO_G24_NONE_P2020 = 21,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_LEFT_P709 = 22,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_LEFT_P2020 = 23,
            DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_TOPLEFT_P2020 = 24,
            DXGI_COLOR_SPACE_CUSTOM = 0xFFFFFFFF
        }

        public enum DXGI_SWAP_EFFECT
        {
            DXGI_SWAP_EFFECT_DISCARD = 0,
            DXGI_SWAP_EFFECT_SEQUENTIAL = 1,
            DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL = 3,
            DXGI_SWAP_EFFECT_FLIP_DISCARD = 4
        }

        public enum DXGI_ALPHA_MODE : uint
        {
            DXGI_ALPHA_MODE_UNSPECIFIED = 0,
            DXGI_ALPHA_MODE_PREMULTIPLIED = 1,
            DXGI_ALPHA_MODE_STRAIGHT = 2,
            DXGI_ALPHA_MODE_IGNORE = 3,
            DXGI_ALPHA_MODE_FORCE_DWORD = 0xffffffff
        }

        public enum DXGI_SCALING
        {
            DXGI_SCALING_STRETCH = 0,
            DXGI_SCALING_NONE = 1,
            DXGI_SCALING_ASPECT_RATIO_STRETCH = 2
        }

        [Flags]
        public enum DXGI_ADAPTER_FLAG3 : uint
        {
            DXGI_ADAPTER_FLAG3_NONE = 0,
            DXGI_ADAPTER_FLAG3_REMOTE = 1,
            DXGI_ADAPTER_FLAG3_SOFTWARE = 2,
            DXGI_ADAPTER_FLAG3_ACG_COMPATIBLE = 4,
            DXGI_ADAPTER_FLAG3_SUPPORT_MONITORED_FENCES = 8,
            DXGI_ADAPTER_FLAG3_SUPPORT_NON_MONITORED_FENCES = 0x10,
            DXGI_ADAPTER_FLAG3_KEYED_MUTEX_CONFORMANCE = 0x20,
            DXGI_ADAPTER_FLAG3_FORCE_DWORD = 0xffffffff
        }

        public enum DXGI_MEMORY_SEGMENT_GROUP
        {
            DXGI_MEMORY_SEGMENT_GROUP_LOCAL = 0,
            DXGI_MEMORY_SEGMENT_GROUP_NON_LOCAL = 1
        }

        public enum DXGI_GPU_PREFERENCE
        {
            DXGI_GPU_PREFERENCE_UNSPECIFIED = 0,
            DXGI_GPU_PREFERENCE_MINIMUM_POWER,
            DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE
        }

        [Flags]
        public enum DXGI_SWAP_CHAIN_FLAG
        {
            DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1,
            DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2,
            DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4,
            DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8,
            DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 16,
            DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 32,
            DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 64,
            DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 128,
            DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 256,
            DXGI_SWAP_CHAIN_FLAG_YUV_VIDEO = 512,
            DXGI_SWAP_CHAIN_FLAG_HW_PROTECTED = 1024,
            DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING = 2048,
            DXGI_SWAP_CHAIN_FLAG_RESTRICTED_TO_ALL_HOLOGRAPHIC_DISPLAYS = 4096
        }

        [Flags]
        public enum DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG
        {
            DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG_PRESENT = 0x1,
            DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG_OVERLAY_PRESENT = 0x2
        }

        public enum DXGI_RESIDENCY
        {
            DXGI_RESIDENCY_FULLY_RESIDENT = 1,
            DXGI_RESIDENCY_RESIDENT_IN_SHARED_MEMORY = 2,
            DXGI_RESIDENCY_EVICTED_TO_DISK = 3
        }

        public enum _DXGI_RECLAIM_RESOURCE_RESULTS
        {
            DXGI_RECLAIM_RESOURCE_RESULT_OK = 0,
            DXGI_RECLAIM_RESOURCE_RESULT_DISCARDED = 1,
            DXGI_RECLAIM_RESOURCE_RESULT_NOT_COMMITTED = 2
        }

        [Flags]
        public enum DXGI_OVERLAY_SUPPORT_FLAG
        {
            DXGI_OVERLAY_SUPPORT_FLAG_DIRECT = 0x1,
            DXGI_OVERLAY_SUPPORT_FLAG_SCALING = 0x2
        }

        [Flags]
        public enum DXGI_OVERLAY_COLOR_SPACE_SUPPORT_FLAG
        {
            DXGI_OVERLAY_COLOR_SPACE_SUPPORT_FLAG_PRESENT = 0x1
        }

        public enum DXGI_OUTDUPL_POINTER_SHAPE_TYPE
        {
            DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROME = 0x1,
            DXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR = 0x2,
            DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR = 0x4
        }

        public enum _DXGI_OFFER_RESOURCE_PRIORITY
        {
            DXGI_OFFER_RESOURCE_PRIORITY_LOW = 1,
            DXGI_OFFER_RESOURCE_PRIORITY_NORMAL,
            DXGI_OFFER_RESOURCE_PRIORITY_HIGH
        }

        [Flags]
        public enum _DXGI_OFFER_RESOURCE_FLAGS
        {
            DXGI_OFFER_RESOURCE_FLAG_ALLOW_DECOMMIT = 0x1
        }

        [Flags]
        public enum DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAGS
        {
            DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAG_NOMINAL_RANGE = 0x1,
            DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAG_BT709 = 0x2,
            DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAG_xvYCC = 0x4
        }

        public enum DXGI_HDR_METADATA_TYPE
        {
            DXGI_HDR_METADATA_TYPE_NONE = 0,
            DXGI_HDR_METADATA_TYPE_HDR10 = 1,
            DXGI_HDR_METADATA_TYPE_HDR10PLUS = 2
        }

        [Flags]
        public enum DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS
        {
            DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_FULLSCREEN = 1,
            DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_WINDOWED = 2,
            DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_CURSOR_STRETCHED = 4
        }

        public enum DXGI_FEATURE
        {
            DXGI_FEATURE_PRESENT_ALLOW_TEARING = 0
        }

        [Flags]
        public enum DXGI_DEBUG_RLO_FLAGS
        {
            DXGI_DEBUG_RLO_SUMMARY = 0x1,
            DXGI_DEBUG_RLO_DETAIL = 0x2,
            DXGI_DEBUG_RLO_IGNORE_INTERNAL = 0x4,
            DXGI_DEBUG_RLO_ALL = 0x7
        }

        [Flags]
        public enum DXGI_ADAPTER_FLAG : uint
        {
            DXGI_ADAPTER_FLAG_NONE = 0,
            DXGI_ADAPTER_FLAG_REMOTE = 1,
            DXGI_ADAPTER_FLAG_SOFTWARE = 2,
            DXGI_ADAPTER_FLAG_FORCE_DWORD = 0xffffffff
        }

        public enum D3D12_SHADER_MIN_PRECISION_SUPPORT
        {
            D3D12_SHADER_MIN_PRECISION_SUPPORT_NONE = 0,
            D3D12_SHADER_MIN_PRECISION_SUPPORT_10_BIT = 0x1,
            D3D12_SHADER_MIN_PRECISION_SUPPORT_16_BIT = 0x2
        }

        public enum D3D12_TILED_RESOURCES_TIER
        {
            D3D12_TILED_RESOURCES_TIER_NOT_SUPPORTED = 0,
            D3D12_TILED_RESOURCES_TIER_1 = 1,
            D3D12_TILED_RESOURCES_TIER_2 = 2,
            D3D12_TILED_RESOURCES_TIER_3 = 3,
            D3D12_TILED_RESOURCES_TIER_4 = 4
        }

        public enum D3D12_RESOURCE_BINDING_TIER
        {
            D3D12_RESOURCE_BINDING_TIER_1 = 1,
            D3D12_RESOURCE_BINDING_TIER_2 = 2,
            D3D12_RESOURCE_BINDING_TIER_3 = 3
        }

        public enum D3D12_CONSERVATIVE_RASTERIZATION_TIER
        {
            D3D12_CONSERVATIVE_RASTERIZATION_TIER_NOT_SUPPORTED = 0,
            D3D12_CONSERVATIVE_RASTERIZATION_TIER_1 = 1,
            D3D12_CONSERVATIVE_RASTERIZATION_TIER_2 = 2,
            D3D12_CONSERVATIVE_RASTERIZATION_TIER_3 = 3
        }

        public enum D3D12_CROSS_NODE_SHARING_TIER
        {
            D3D12_CROSS_NODE_SHARING_TIER_NOT_SUPPORTED = 0,
            D3D12_CROSS_NODE_SHARING_TIER_1_EMULATED = 1,
            D3D12_CROSS_NODE_SHARING_TIER_1 = 2,
            D3D12_CROSS_NODE_SHARING_TIER_2 = 3,
            D3D12_CROSS_NODE_SHARING_TIER_3 = 4
        }

        public enum D3D12_RESOURCE_HEAP_TIER
        {
            D3D12_RESOURCE_HEAP_TIER_1 = 1,
            D3D12_RESOURCE_HEAP_TIER_2 = 2
        }

        [Flags]
        public enum DXGI_USAGE : uint
        {
            DXGI_USAGE_SHADER_INPUT = 0x10,
            DXGI_USAGE_RENDER_TARGET_OUTPUT = 0x20,
            DXGI_USAGE_BACK_BUFFER = 0x40,
            DXGI_USAGE_SHARED = 0x80,
            DXGI_USAGE_READ_ONLY = 0x100,
            DXGI_USAGE_DISCARD_ON_PRESENT = 0x200,
            DXGI_USAGE_UNORDERED_ACCESS = 0x400,
        }
    }
}
